export POSTGRES_USER=brian
export POSTGRES_PASSWORD=1234
export POSTGRES_DB=crud
export POSTGRES_HOST=127.0.0.1
export POSTGRES_PORT=5432
export POSTGRES_SSL=disable
export POSTGRES_TIMEZONE=Asia/Jakarta
