export POSTGRES_USER= # DATABASE USER
export POSTGRES_PASSWORD= # DATABASE PASSWORD
export POSTGRES_DB= # DATABASE NAME
export POSTGRES_HOST= # DATABASE HOST IP
export POSTGRES_PORT= # DATABASE PORT NAME
export POSTGRES_SSL= # SSL MODE = disable/enable
export POSTGRES_TIMEZONE= # YOUR SERVER's TIMEZONE

export JWT_KEY= # YOUR JWT SECRET KEY
