export POSTGRES_USER=brian # DATABASE USER
export POSTGRES_PASSWORD=srin # DATABASE PASSWORD
export POSTGRES_DB=crud # DATABASE NAME
export POSTGRES_HOST=127.0.0.1 # DATABASE HOST IP
export POSTGRES_PORT=5432 # DATABASE PORT NAME
export POSTGRES_SSL=disable # SSL MODE = disable/enable
export POSTGRES_TIMEZONE=Asia/Jakarta # YOUR SERVER's TIMEZONE

export JWT_KEY=secretkey # YOUR JWT SECRET KEY
